export const REQUEST_DATABASES = 'REQUEST_DATABASES';
export const RECEIVE_DATABASES = 'RECEIVE_DATABASES';
export const REQUEST_DB_STATS = 'REQUEST_DB_STATS';
export const RECEIVE_DB_STATS = 'RECEIVE_DB_STATS';
export const REQUEST_COLLECTIONS = 'REQUEST_COLLECTIONS';
export const RECEIVE_COLLECTIONS = 'RECEIVE_COLLECTIONS';
export const REQUEST_DOCS = 'REQUEST_DOCS';
export const RECEIVE_DOCS = 'RECEIVE_DOCS';
export const FILTER_DOCS = 'FILTER_DOCS';
export const REMOVE_DOC = 'REMOVE_DOC';
export const UPDATE_DOC = 'UPDATE_DOC';
export const SELECT_DB = 'SELECT_DB';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const SELECT_COLLECTION = 'SELECT_COLLECTION';
export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const RENAME_COLLECTION = 'RENAME_COLLECTION';
export const DROP_COLLECTION = 'DROP_COLLECTION';

export const SET_VIEW_MODE = 'SET_VIEW_MODE';

export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const MESSAGE_ERROR = 'error';
export const MESSAGE_SUCCESS = 'success';

export const CONFIRMATION = 'CONFIRMATION';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const API_URL = 'http://localhost:3000';
